-- begin BANK_GASENJE_RACUNA
alter table BANK_GASENJE_RACUNA add constraint FK_BANK_GASENJE_RACUNA_ON_RACUN_ZA_GASENJE foreign key (RACUN_ZA_GASENJE_ID) references BANK_RACUN(ID)^
create index IDX_BANK_GASENJE_RACUNA_ON_RACUN_ZA_GASENJE on BANK_GASENJE_RACUNA (RACUN_ZA_GASENJE_ID)^
-- end BANK_GASENJE_RACUNA
-- begin BANK_DNEVNO_STANJE
alter table BANK_DNEVNO_STANJE add constraint FK_BANK_DNEVNO_STANJE_ON_RACUN foreign key (RACUN_ID) references BANK_RACUN(ID)^
create index IDX_BANK_DNEVNO_STANJE_ON_RACUN on BANK_DNEVNO_STANJE (RACUN_ID)^
-- end BANK_DNEVNO_STANJE
-- begin BANK_BANKA
alter table BANK_BANKA add constraint FK_BANK_BANKA_ON_MESTO foreign key (MESTO_ID) references BANK_MESTO(ID)^
create unique index IDX_BANK_BANKA_UNIQ_SIFRA_BANKE on BANK_BANKA (SIFRA_BANKE)^
create unique index IDX_BANK_BANKA_UNIQ_SWIFT_KOD on BANK_BANKA (SWIFT_KOD)^
create unique index IDX_BANK_BANKA_UNIQ_OBRACUNSKI_RACUN on BANK_BANKA (OBRACUNSKI_RACUN)^
create index IDX_BANK_BANKA_ON_MESTO on BANK_BANKA (MESTO_ID)^
-- end BANK_BANKA
-- begin BANK_SIFARNIK_DELATNOSTI
create unique index IDX_BANK_SIFARNIK_DELATNOSTI_UNIQ_SIFRA_DELATNOSTI on BANK_SIFARNIK_DELATNOSTI (SIFRA_DELATNOSTI)^
-- end BANK_SIFARNIK_DELATNOSTI
-- begin BANK_MESTO
create unique index IDX_BANK_MESTO_UNIQ_POSTANSKI_BROJ on BANK_MESTO (POSTANSKI_BROJ)^
-- end BANK_MESTO
-- begin BANK_KLIJENT
alter table BANK_KLIJENT add constraint FK_BANK_KLIJENT_ON_MESTO foreign key (MESTO_ID) references BANK_MESTO(ID)^
alter table BANK_KLIJENT add constraint FK_BANK_KLIJENT_ON_DELATNOST foreign key (DELATNOST_ID) references BANK_SIFARNIK_DELATNOSTI(ID)^
create unique index IDX_BANK_KLIJENT_UNIQ_JMBG on BANK_KLIJENT (JMBG)^
create index IDX_BANK_KLIJENT_ON_MESTO on BANK_KLIJENT (MESTO_ID)^
create index IDX_BANK_KLIJENT_ON_DELATNOST on BANK_KLIJENT (DELATNOST_ID)^
-- end BANK_KLIJENT

-- begin BANK_NALOG
alter table BANK_NALOG add constraint FK_BANK_NALOG_ON_DNEVNO_STANJE foreign key (DNEVNO_STANJE_ID) references BANK_DNEVNO_STANJE(ID)^
alter table BANK_NALOG add constraint FK_BANK_NALOG_ON_PORUKA foreign key (PORUKA_ID) references BANK_PORUKA(ID)^
create index IDX_BANK_NALOG_ON_DNEVNO_STANJE on BANK_NALOG (DNEVNO_STANJE_ID)^
create index IDX_BANK_NALOG_ON_PORUKA on BANK_NALOG (PORUKA_ID)^
-- end BANK_NALOG
-- begin BANK_RACUN
alter table BANK_RACUN add constraint FK_BANK_RACUN_ON_BANKA foreign key (BANKA_ID) references BANK_BANKA(ID)^
alter table BANK_RACUN add constraint FK_BANK_RACUN_ON_KLIJENT foreign key (KLIJENT_ID) references BANK_KLIJENT(ID)^
create unique index IDX_BANK_RACUN_UNIQ_BROJ_RACUNA on BANK_RACUN (BROJ_RACUNA)^
create index IDX_BANK_RACUN_ON_BANKA on BANK_RACUN (BANKA_ID)^
create index IDX_BANK_RACUN_ON_KLIJENT on BANK_RACUN (KLIJENT_ID)^
-- end BANK_RACUN
-- begin BANK_PORUKA
alter table BANK_PORUKA add constraint FK_BANK_PORUKA_ON_BANKA_POVERIOCA foreign key (BANKA_POVERIOCA_ID) references BANK_BANKA(ID)^
alter table BANK_PORUKA add constraint FK_BANK_PORUKA_ON_BANKA_DUZNIKA foreign key (BANKA_DUZNIKA_ID) references BANK_BANKA(ID)^
create index IDX_BANK_PORUKA_ON_BANKA_POVERIOCA on BANK_PORUKA (BANKA_POVERIOCA_ID)^
create index IDX_BANK_PORUKA_ON_BANKA_DUZNIKA on BANK_PORUKA (BANKA_DUZNIKA_ID)^
-- end BANK_PORUKA
-- begin BANK_SLUZBENIK
alter table BANK_SLUZBENIK add constraint FK_BANK_SLUZBENIK_ON_BANKA foreign key (BANKA_ID) references BANK_BANKA(ID)^
create unique index IDX_BANK_SLUZBENIK_UNIQ_EMAIL on BANK_SLUZBENIK (EMAIL)^
create unique index IDX_BANK_SLUZBENIK_UNIQ_JMBG on BANK_SLUZBENIK (JMBG)^
create index IDX_BANK_SLUZBENIK_ON_BANKA on BANK_SLUZBENIK (BANKA_ID)^
-- end BANK_SLUZBENIK
