alter table BANK_BANKA add constraint FK_BANK_BANKA_ON_MESTO foreign key (MESTO_ID) references BANK_MESTO(ID);
create unique index IDX_BANK_BANKA_UNIQ_SIFRA_BANKE on BANK_BANKA (SIFRA_BANKE);
create unique index IDX_BANK_BANKA_UNIQ_SWIFT_KOD on BANK_BANKA (SWIFT_KOD);
create unique index IDX_BANK_BANKA_UNIQ_OBRACUNSKI_RACUN on BANK_BANKA (OBRACUNSKI_RACUN);
create index IDX_BANK_BANKA_ON_MESTO on BANK_BANKA (MESTO_ID);
