alter table BANK_KLIJENT add constraint FK_BANK_KLIJENT_ON_MESTO foreign key (MESTO_ID) references BANK_MESTO(ID);
alter table BANK_KLIJENT add constraint FK_BANK_KLIJENT_ON_DELATNOST foreign key (DELATNOST_ID) references BANK_SIFARNIK_DELATNOSTI(ID);
create unique index IDX_BANK_KLIJENT_UNIQ_JMBG on BANK_KLIJENT (JMBG);
create index IDX_BANK_KLIJENT_ON_MESTO on BANK_KLIJENT (MESTO_ID);
create index IDX_BANK_KLIJENT_ON_DELATNOST on BANK_KLIJENT (DELATNOST_ID);
