alter table BANK_KLIJENT add constraint FK_BANK_KLIJENT_ON_DELATNOST foreign key (DELATNOST_ID) references BANK_SIFARNIK_DELATNOSTI(ID);
create index IDX_BANK_KLIJENT_ON_DELATNOST on BANK_KLIJENT (DELATNOST_ID);
